base_app/urls.py
from django.urls import path

from . import views

app_name = "base_app"

urlpatterns = [
    path('survey1/', views.Survey1View.as_view(), name='survey1'),
    path('survey2/', views.Survey2View.as_view(), name='survey2'),
    path('create-survey1/', views.CreateSurvey1.as_view(), name='create_survey1'),
    path('create-survey2/', views.CreateSurvey2.as_view(), name='create_survey2'),

]

feedback_survey/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.views.static import serve
from base_app import views as general_views
from feedback_survey import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='dashboard', permanent=False), name='feedback_survey'),
    path('dashboard', general_views.DashboardView.as_view(), name='dashboard'),
    path('survey1', general_views.Survey1View.as_view(), name='survey1'),
    path('survey2', general_views.Survey2View.as_view(), name='survey2'),

    path('course-feedback/', include('base_app.urls', namespace='course_feedback')),
    path('static/<path:path>/', serve, {'document_root': settings.STATIC_FILE_ROOT, }),

]

base_app/models.py
from django.db import models
from django.utils import timezone


class BaseModel(models.Model):
    """Base model extended by other models through out the project.
        Here we define all the common fields used by all the models used in the project.
    """

    date_added = models.DateTimeField(db_index=True)
    date_updated = models.DateTimeField()

    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        """Overriding the save methods to extend the logic."""

        if self.is_deleted is False:
            self.date_added = timezone.now()
            self.date_updated = timezone.now()

        super(BaseModel, self).save(*args, **kwargs)


class Student(BaseModel):
    student_id = models.CharField(max_length=128, unique=True, db_index=True)
    student_name = models.CharField(max_length=128)
    email = models.EmailField(unique=True)

    class Meta:
        db_table = 'students'
        ordering = ['date_added', '-student_id']

    def __str__(self):
        return "{} :{}".format(self.student_name, self.student_id)

    def save(self, *args, **kwargs):
        super(Student, self).save(*args, **kwargs)


class Course(BaseModel):
    course_id = models.CharField(max_length=128, unique=True, db_index=True)
    course_name = models.CharField(max_length=128)

    class Meta:
        db_table = 'course'
        ordering = ['date_added', '-course_id']

    def __str__(self):
        return "{} :{}".format(self.course_name, self.course_id)

    def save(self, *args, **kwargs):
        super(Course, self).save(*args, **kwargs)


class SemesterOffering(BaseModel):
    semester_offering_id = models.CharField(max_length=128, unique=True, db_index=True)
    semester_name = models.CharField(max_length=128)
    course = models.ForeignKey('Course', on_delete=models.PROTECT,null=True)
    start_date = models.DateField(db_index=True, null=True)
    end_date = models.DateField(db_index=True, null=True)

    class Meta:
        db_table = 'semester_offering'
        ordering = ['date_added', '-semester_offering_id']

    def __str__(self):
        return "{} :{}".format(self.course, self.semester_offering_id)

    def save(self, *args, **kwargs):
        super(SemesterOffering, self).save(*args, **kwargs)


class StudentCourseRegistration(BaseModel):
    student = models.ForeignKey('Student', on_delete=models.PROTECT,null=True)
    semester_offering = models.ForeignKey('SemesterOffering', on_delete=models.PROTECT, null=True)

    class Meta:
        db_table = 'student_course_registration'

    def __str__(self):
        return "{} :{}".format(self.student, self.semester_offering)

    def save(self, *args, **kwargs):
        super(StudentCourseRegistration, self).save(*args, **kwargs)


class Survey1(BaseModel):
    student_name = models.CharField(max_length=128)
    semester= models.ForeignKey('SemesterOffering', on_delete=models.PROTECT, null=True)
    vote = models.IntegerField(default=1)
    missed_class = models.CharField(max_length=128)

    class Meta:
        db_table = 'survey1'

    def __str__(self):
        return "{} :{}".format(self.student_name, self.semester)

    def save(self, *args, **kwargs):
        super(Survey1, self).save(*args, **kwargs)


class Survey2(BaseModel):
    student_name = models.CharField(max_length=128)
    semester= models.ForeignKey('SemesterOffering', on_delete=models.PROTECT, null=True)
    vote = models.IntegerField(default=1)
    expected_topic = models.CharField(max_length=128)
    is_class_off_time = models.BooleanField(default=False)

    class Meta:
        db_table = 'survey2'

    def __str__(self):
        return "{} :{}".format(self.student_name, self.semester)

    def save(self, *args, **kwargs):
        super(Survey2, self).save(*args, **kwargs)

templates/base.html
<!DOCTYPE html>
<html>
<head>
<!--  -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Feedback Survey </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">  {% load static %}
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'css/ionicons.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.css' %}">

  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'css/_all-skins.css' %}">

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue fixed sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>Survey</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Survey</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

         <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static 'img/a1.jpg' %}" class="user-image" alt="User Image">
              <span class="hidden-xs" id="username_id"></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{% static 'img/a1.jpg' %}" class="img-circle" alt="User Image">
              </li>

            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% static 'img/a1.jpg' %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{request.user}}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="treeview"> <!--active  -->
          <a href="#">
            <i class="fa fa-dashboard"></i>
             <span>Survey</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'course_feedback:create_survey1' %}"><i class="fa fa-circle-o"></i> Survey1</a></li>
            <li><a href="{% url 'course_feedback:create_survey2' %}"><i class="fa fa-circle-o"></i> Survey2</a></li>
          </ul>
        </li>

      </ul>
    </section>
    <!-- /.sidebar -->
</aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block content %}
    {% endblock %}
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>


  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
</div>

{% load static %}

<!-- ./wrapper -->

<!-- jQuery 3 -->


<script src="{% static 'js/jquery.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<!--<script src="{% static 'js/jquery-ui.js' %}"></script>-->

<!--<script src="{% static 'js/jquery-jvectormap-1.2.2.min.js' %}"></script>-->

<!--<script src="{% static 'js/jquery-jvectormap-world-mill-en.js' %}"></script>-->

<!--<script src="{% static 'js/jquery.sparkline.js' %}"></script>-->

<!--<script src="{% static 'js/jquery.knob.min.js' %}"></script>-->

<!--<script src="{% static 'js/jquery.slimscroll.js' %}"></script>-->


<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<!-- <script>
  $.widget.bridge('uibutton', $.ui.button);
</script> -->
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- Morris.js charts -->
<!--<script src="{% static 'js/raphael.js' %}"></script>-->
<!--<script src="{% static 'js/morris.js' %}"></script>-->
<!-- Sparkline -->
<!-- jvectormap -->
<!-- jQuery Knob Chart -->
<!-- daterangepicker -->
<!--<script src="{% static 'js/moment.min.js' %}"></script>-->

 <!-- Bootstrap WYSIHTML5 -->
 <script src="{% static 'js/bootstrap3-wysihtml5.all.js' %}"></script>

<script type="text/javascript">

$(document).ready(function(){
               /** add active class and stay opened when selected */
               var url = window.location;

               // for sidebar menu entirely but not cover treeview
               $('ul.sidebar-menu a').filter(function() {
                    return this.href == url;
               }).parent().addClass('active');

               // for treeview
               $('ul.treeview-menu a').filter(function() {
                    return this.href == url;
               }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
           });
</script>

{% block js %}
{% endblock %}
</body>

</html>

templates/create_survey1.html
{% extends "base.html" %} {% load i18n %}
{% block title %}
<title>Survey1</title>
{% endblock %}

{% block content %}

<div class="content-wrapper">

    <div class="container-fluid">
        <section class="content">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Survey 1</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
              <div class="col-md-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_content">
                    <form id="survey1_form" action="{{url}}" method="post" class="form-horizontal form-label-left ajax reset {% if redirect %}redirect{% endif %}" novalidate="">
                      {% csrf_token %}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.student_name.id_for_label }}">  {{ form.student_name.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.student_name }}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.semester.id_for_label }}">  {{ form.semester.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.semester }}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.vote.id_for_label }}">  {{ form.vote.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.vote}}
                        </div>
                      </div>
                        <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.missed_class.id_for_label }}">  {{ form.missed_class.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.missed_class}}
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <input type="submit" class="btn btn-success" value="Submit">
                        </div>
                      </div>
                    </form>
                </div>
                </div>
            </div>

              <!-- /.box-body -->

              <div class="box-footer">
              </div>
          </div>
          <!-- /.box -->
        </section>
    </div>
</div>
{% endblock %}

templates/create_survey2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>{% extends "base.html" %} {% load i18n %}
{% block title %}
<title>Survey2</title>
{% endblock %}

{% block content %}
<div class="content-wrapper">

    <div class="container-fluid">
        <section class="content">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Survey 2</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
              <form id="survey1_form" action="{{url}}" method="post" class="form-horizontal form-label-left ajax reset {% if redirect %}redirect{% endif %}" novalidate="">
                      {% csrf_token %}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.student_name.id_for_label }}">  {{ form.student_name.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.student_name }}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.semester.id_for_label }}">  {{ form.semester.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.semester }}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.vote.id_for_label }}">  {{ form.vote.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.vote}}
                        </div>
                      </div>
                        <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.expected_topic.id_for_label }}">  {{ form.expected_topic.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.expected_topic}}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"  for="{{ form.is_class_off_time.id_for_label }}">  {{ form.is_class_off_time.label }}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{ form.is_class_off_time}}
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <input type="submit" class="btn btn-success" value="Submit">
                        </div>
                      </div>
                    </form>
          </div>
          <!-- /.box -->
        </section>
    </div>
</div>
{% endblock %}

templates/survey1.html
{% extends "base.html" %} {% load i18n %}
{% block title %}
<title>Survey1</title>
{% endblock %}

{% block content %}

<div class="content-wrapper">

    <div class="container-fluid">
        <section class="content">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Survey 1</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form">
              <div class="box-body">
                <div class="form-group">
                  <label for="id_nameInput">Name</label>
                  <input type="text" class="form-control" id="id_nameInput" placeholder="Enter Name">
                </div>
                <div class="form-group">
                  <label for="id_like_course">Did You Like the Course?</label>
                  <input type="text" class="form-control" id="id_like_course" placeholder="Courses ">
                </div>
                <div class="form-group">
                  <label for="id_missed_class">How many classes you missed in the semester (out of 20) ?</label>
                  <input type="text" id="id_missed_class">

                </div>

              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </section>
    </div>
</div>
{% endblock %}

templates/survey2.html
{% extends "base.html" %} {% load i18n %}
{% block title %}
<title>Survey2</title>
{% endblock %}

{% block content %}
<div class="content-wrapper">

    <div class="container-fluid">
        <section class="content">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Survey 2</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form">
              <div class="box-body">
                <div class="form-group">
                  <label for="id_nameInput">Name</label>
                  <input type="text" class="form-control" id="id_nameInput" placeholder="Enter Name">
                </div>
                <div class="form-group">
                  <label for="id_like_course">Did You Like the Course?</label>
                  <input type="text" class="form-control" id="id_like_course" placeholder="Courses ">
                </div>
                <div class="form-group">
                  <label for="id_missed_class">What topics you expected to learn about in the course?</label>
                  <input type="text" id="id_missed_class">

                </div>
                <div class="form-group">
                  <label for="id_class_time">Did the class start and end of time? Yes/No?</label>
                  <input type="text" id="id_class_time">

                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </section>
    </div>
</div>
{% endblock %}